-- AUTO-GENERATED. DO NOT EDIT.
-- Source: live Supabase table DDL versioning
-- Schema:   archive
-- Entity:   tables
-- Mode:     table_bundle
-- Updated:  2026-09-26T22:01:53.920Z

-- table: function_history

CREATE TABLE archive.function_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  schema_name text,
  function_name text,
  args text,
  return_type text,
  source_code text,
  lang_settings text,
  updated_at timestamp with time zone DEFAULT now(),
  version numeric DEFAULT 1,
  active boolean NOT NULL DEFAULT false,
  CONSTRAINT function_history_pkey PRIMARY KEY (id)
);
CREATE TRIGGER before_insert_function_history BEFORE INSERT ON archive.function_history FOR EACH ROW EXECUTE FUNCTION calculate_function_version();

-- table: function_versioning_settings

CREATE TABLE archive.function_versioning_settings (
  singleton boolean NOT NULL DEFAULT true,
  edge_base_url text NOT NULL,
  CONSTRAINT function_versioning_settings_pkey PRIMARY KEY (singleton),
  CONSTRAINT function_versioning_settings_singleton_check CHECK (singleton)
);

-- table: github_push_queue

CREATE TABLE archive.github_push_queue (
  id bigint NOT NULL DEFAULT nextval('github_push_queue_id_seq'::regclass),
  function_history_id bigint,
  publish_token uuid NOT NULL DEFAULT extensions.gen_random_uuid(),
  status text NOT NULL DEFAULT 'pending'::text,
  try_count integer NOT NULL DEFAULT 0,
  last_error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  pushed_at timestamp with time zone,
  item_type text NOT NULL DEFAULT 'function'::text,
  table_history_id bigint,
  schema_name text,
  CONSTRAINT github_push_queue_function_history_id_fkey FOREIGN KEY (function_history_id) REFERENCES function_history(id) ON DELETE CASCADE,
  CONSTRAINT github_push_queue_item_ref_check CHECK (item_type = 'function'::text AND function_history_id IS NOT NULL AND table_history_id IS NULL AND schema_name IS NULL OR item_type = 'table_bundle'::text AND function_history_id IS NULL AND table_history_id IS NOT NULL AND schema_name IS NOT NULL),
  CONSTRAINT github_push_queue_item_type_check CHECK (item_type = ANY (ARRAY['function'::text, 'table_bundle'::text])),
  CONSTRAINT github_push_queue_pkey PRIMARY KEY (id),
  CONSTRAINT github_push_queue_status_check CHECK (status = ANY (ARRAY['pending'::text, 'done'::text, 'dead'::text])),
  CONSTRAINT github_push_queue_table_history_id_fkey FOREIGN KEY (table_history_id) REFERENCES table_history(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX github_push_queue_function_history_id_uidx ON archive.github_push_queue USING btree (function_history_id);
CREATE UNIQUE INDEX github_push_queue_publish_token_uidx ON archive.github_push_queue USING btree (publish_token);
CREATE INDEX github_push_queue_status_idx ON archive.github_push_queue USING btree (status, id);
CREATE UNIQUE INDEX github_push_queue_table_history_id_uidx ON archive.github_push_queue USING btree (table_history_id) WHERE (item_type = 'table_bundle'::text);

-- table: schema_export_snapshots

CREATE TABLE archive.schema_export_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  snapshot jsonb NOT NULL,
  publish_token uuid NOT NULL DEFAULT extensions.gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  published_at timestamp with time zone,
  CONSTRAINT schema_export_snapshots_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX schema_export_snapshots_publish_token_uidx ON archive.schema_export_snapshots USING btree (publish_token);
CREATE INDEX schema_export_snapshots_created_at_idx ON archive.schema_export_snapshots USING btree (created_at DESC);

-- table: table_history

CREATE TABLE archive.table_history (
  id bigint NOT NULL DEFAULT nextval('table_history_id_seq'::regclass),
  schema_name text NOT NULL,
  table_name text NOT NULL,
  ddl text NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  version integer NOT NULL DEFAULT 1,
  active boolean NOT NULL DEFAULT false,
  dropped boolean NOT NULL DEFAULT false,
  CONSTRAINT table_history_pkey PRIMARY KEY (id)
);
CREATE INDEX table_history_lookup_idx ON archive.table_history USING btree (schema_name, table_name, id DESC);
CREATE INDEX table_history_active_idx ON archive.table_history USING btree (schema_name, table_name) WHERE (active = true);
