-- Historical migration marker.
-- This version already exists in the linked DanceApp remote migration history.
-- Original legacy DDL is intentionally not replayed in dance-crm.
-- Clean schema work starts after this reconciled history.
-- Original migration: 20260913123537_social_queue_fairness
