create extension if not exists http with schema extensions;
create schema if not exists archive;

create table if not exists archive.function_history (
  id bigint generated by default as identity primary key,
  schema_name text,
  function_name text,
  args text,
  return_type text,
  source_code text,
  lang_settings text,
  updated_at timestamptz default now(),
  version numeric default 1,
  active boolean not null default false
);

alter table archive.function_history
  add column if not exists active boolean not null default false;

with ranked as (
  select
    id,
    row_number() over (
      partition by schema_name, function_name, args, return_type, lang_settings
      order by id desc
    ) as rn
  from archive.function_history
)
update archive.function_history fh
set active = (ranked.rn = 1)
from ranked
where ranked.id = fh.id;

create or replace view archive.latest_function_versions as
select *
from archive.function_history
where active = true
order by schema_name, function_name, args, return_type;

create or replace function archive.diff_text(old_text text, new_text text)
returns table(line_no integer, old_line text, new_line text)
language sql
as $function$
  select
    row_number() over ()::integer as line_no,
    o.line,
    n.line
  from regexp_split_to_table(coalesce(old_text, ''), E'\n')
    with ordinality o(line, ord)
  full join regexp_split_to_table(coalesce(new_text, ''), E'\n')
    with ordinality n(line, ord)
    using (ord)
  where o.line is distinct from n.line;
$function$;

create or replace function archive.save_function_history(
  function_name text,
  args text,
  return_type text,
  source_code text,
  schema_name text default 'public',
  lang_settings text default 'plpgsql'
)
returns void
language plpgsql
security definer
set search_path to 'public', 'archive'
as $function$
declare
  v_prev_id bigint;
  v_prev_code text;
begin
  select fh.id, fh.source_code
  into v_prev_id, v_prev_code
  from archive.function_history fh
  where fh.schema_name = save_function_history.schema_name
    and fh.function_name = save_function_history.function_name
    and fh.args = save_function_history.args
    and fh.return_type = save_function_history.return_type
    and fh.lang_settings = save_function_history.lang_settings
  order by fh.id desc
  limit 1;

  if v_prev_code is not null and not exists (
    select 1 from archive.diff_text(v_prev_code, source_code)
  ) then
    update archive.function_history fh
    set active = false
    where fh.schema_name = save_function_history.schema_name
      and fh.function_name = save_function_history.function_name
      and fh.args = save_function_history.args
      and fh.return_type = save_function_history.return_type
      and fh.lang_settings = save_function_history.lang_settings;

    update archive.function_history
    set active = true
    where id = v_prev_id;

    return;
  end if;

  update archive.function_history fh
  set active = false
  where fh.schema_name = save_function_history.schema_name
    and fh.function_name = save_function_history.function_name
    and fh.args = save_function_history.args
    and fh.return_type = save_function_history.return_type
    and fh.lang_settings = save_function_history.lang_settings;

  insert into archive.function_history (
    schema_name,
    function_name,
    args,
    return_type,
    source_code,
    lang_settings,
    active
  )
  values (
    schema_name,
    function_name,
    args,
    return_type,
    source_code,
    lang_settings,
    true
  );
end;
$function$;

create or replace function archive.update_function_history(
  function_name text,
  args text,
  return_type text,
  source_code text,
  schema_name text default 'public',
  lang_settings text default 'plpgsql'
)
returns boolean
language plpgsql
security definer
set search_path to 'public', 'archive'
as $function$
declare
  v_prev_id bigint;
  v_prev_code text;
  v_prev_active boolean;
begin
  select fh.id, fh.source_code, fh.active
  into v_prev_id, v_prev_code, v_prev_active
  from archive.function_history fh
  where fh.schema_name = update_function_history.schema_name
    and fh.function_name = update_function_history.function_name
    and fh.args = update_function_history.args
    and fh.return_type = update_function_history.return_type
    and fh.lang_settings = update_function_history.lang_settings
  order by fh.id desc
  limit 1;

  if v_prev_code is not null and not exists (
    select 1 from archive.diff_text(v_prev_code, source_code)
  ) then
    if not v_prev_active then
      update archive.function_history fh
      set active = false
      where fh.schema_name = update_function_history.schema_name
        and fh.function_name = update_function_history.function_name
        and fh.args = update_function_history.args
        and fh.return_type = update_function_history.return_type
        and fh.lang_settings = update_function_history.lang_settings;

      update archive.function_history
      set active = true
      where id = v_prev_id;
    end if;

    return false;
  end if;

  update archive.function_history fh
  set active = false
  where fh.schema_name = update_function_history.schema_name
    and fh.function_name = update_function_history.function_name
    and fh.args = update_function_history.args
    and fh.return_type = update_function_history.return_type
    and fh.lang_settings = update_function_history.lang_settings;

  insert into archive.function_history (
    schema_name,
    function_name,
    args,
    return_type,
    source_code,
    lang_settings,
    active
  )
  values (
    schema_name,
    function_name,
    args,
    return_type,
    source_code,
    lang_settings,
    true
  );

  return true;
end;
$function$;

create or replace function archive.update_functions(schema_name text default 'public')
returns table(
  function_history_id bigint,
  schema text,
  function_name text,
  args text,
  return_type text
)
language plpgsql
as $function$
declare
  function_record record;
  v_changed boolean;
  v_last_id bigint;
begin
  update archive.function_history fh
  set active = false
  where fh.schema_name = update_functions.schema_name;

  for function_record in (
    select
      n.nspname as schema_name,
      p.proname as function_name,
      pg_catalog.pg_get_function_arguments(p.oid) as args,
      pg_catalog.pg_get_function_result(p.oid) as return_type,
      pg_catalog.pg_get_functiondef(p.oid) as source_code,
      l.lanname as lang_settings
    from pg_catalog.pg_proc p
    join pg_catalog.pg_namespace n on n.oid = p.pronamespace
    join pg_catalog.pg_language l on l.oid = p.prolang
    where n.nspname = update_functions.schema_name
      and p.prokind = 'f'
  )
  loop
    v_changed := archive.update_function_history(
      function_record.function_name,
      function_record.args,
      function_record.return_type,
      function_record.source_code,
      function_record.schema_name,
      function_record.lang_settings
    );

    if v_changed then
      select fh.id
      into v_last_id
      from archive.function_history fh
      where fh.schema_name = function_record.schema_name
        and fh.function_name = function_record.function_name
        and fh.args = function_record.args
        and fh.return_type = function_record.return_type
        and fh.lang_settings = function_record.lang_settings
      order by fh.id desc
      limit 1;

      function_history_id := v_last_id;
      schema := function_record.schema_name;
      function_name := function_record.function_name;
      args := function_record.args;
      return_type := function_record.return_type;
      return next;
    end if;
  end loop;
end;
$function$;

create or replace function archive.setup_function_history(
  schema_name text default 'public'
)
returns void
language plpgsql
as $function$
declare
  function_record record;
begin
  update archive.function_history fh
  set active = false
  where fh.schema_name = setup_function_history.schema_name;

  for function_record in (
    select
      n.nspname as schema_name,
      p.proname as function_name,
      pg_catalog.pg_get_function_arguments(p.oid) as args,
      pg_catalog.pg_get_function_result(p.oid) as return_type,
      pg_catalog.pg_get_functiondef(p.oid) as source_code,
      l.lanname as lang_settings
    from pg_catalog.pg_proc p
    join pg_catalog.pg_namespace n on n.oid = p.pronamespace
    join pg_catalog.pg_language l on l.oid = p.prolang
    where n.nspname = setup_function_history.schema_name
      and p.prokind = 'f'
  )
  loop
    perform archive.save_function_history(
      function_record.function_name,
      function_record.args,
      function_record.return_type,
      function_record.source_code,
      function_record.schema_name,
      function_record.lang_settings
    );
  end loop;
end;
$function$;

create table if not exists archive.github_push_queue (
  id bigint generated by default as identity primary key,
  function_history_id bigint not null
    references archive.function_history(id) on delete cascade,
  publish_token uuid not null default extensions.gen_random_uuid(),
  status text not null default 'pending',
  try_count integer not null default 0,
  last_error text,
  created_at timestamptz not null default now(),
  pushed_at timestamptz
);

alter table archive.github_push_queue
  add column if not exists publish_token uuid;

update archive.github_push_queue
set publish_token = extensions.gen_random_uuid()
where publish_token is null;

alter table archive.github_push_queue
  alter column publish_token set default extensions.gen_random_uuid(),
  alter column publish_token set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'archive.github_push_queue'::regclass
      and conname = 'github_push_queue_status_check'
  ) then
    alter table archive.github_push_queue
      add constraint github_push_queue_status_check
      check (status in ('pending', 'done', 'dead'));
  end if;
end
$$;

create unique index if not exists github_push_queue_function_history_id_uidx
  on archive.github_push_queue(function_history_id);

create unique index if not exists github_push_queue_publish_token_uidx
  on archive.github_push_queue(publish_token);

create index if not exists github_push_queue_status_idx
  on archive.github_push_queue(status, id);

create table if not exists archive.function_versioning_settings (
  singleton boolean primary key default true check (singleton),
  edge_base_url text not null
);

insert into archive.function_versioning_settings(singleton, edge_base_url)
values (
  true,
  'https://acmgtkethcijxgldrfgw.supabase.co/functions/v1'
)
on conflict (singleton) do update
set edge_base_url = excluded.edge_base_url;

create or replace function archive.redact_function_source(p_source text)
returns text
language sql
immutable
as $function$
  select regexp_replace(
    regexp_replace(
      regexp_replace(
        coalesce(p_source, ''),
        '[0-9]{7,12}:[A-Za-z0-9_-]{25,}',
        '<REDACTED_LEGACY_TELEGRAM_BOT_TOKEN>',
        'g'
      ),
      'sb_secret_[A-Za-z0-9_-]{10,}',
      '<REDACTED_SUPABASE_SECRET_KEY>',
      'g'
    ),
    'eyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}',
    '<REDACTED_JWT>',
    'g'
  );
$function$;

create or replace function public.get_function_publish_payload(
  p_function_history_id bigint,
  p_publish_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_schema text;
  v_function_name text;
  v_payload jsonb;
begin
  if not exists (
    select 1
    from archive.github_push_queue q
    where q.function_history_id = p_function_history_id
      and q.publish_token = p_publish_token
      and q.status = 'pending'
      and q.try_count < 10
  ) then
    raise exception 'invalid or inactive publish token'
      using errcode = '42501';
  end if;

  select fh.schema_name, fh.function_name
  into v_schema, v_function_name
  from archive.function_history fh
  where fh.id = p_function_history_id;

  if v_schema is null or v_function_name is null then
    raise exception 'function history row not found'
      using errcode = 'P0002';
  end if;

  select jsonb_build_object(
    'schema', v_schema,
    'function_name', v_function_name,
    'overloads', coalesce(
      jsonb_agg(
        jsonb_build_object(
          'language', fh.lang_settings,
          'args', fh.args,
          'return_type', fh.return_type,
          'source_code', archive.redact_function_source(fh.source_code)
        )
        order by fh.lang_settings, fh.args, fh.return_type
      ),
      '[]'::jsonb
    )
  )
  into v_payload
  from archive.function_history fh
  where fh.schema_name = v_schema
    and fh.function_name = v_function_name
    and fh.active = true;

  return v_payload;
end;
$function$;

revoke all on function public.get_function_publish_payload(bigint, uuid)
from public, anon, authenticated;
grant execute on function public.get_function_publish_payload(bigint, uuid)
to service_role;

create or replace function archive.github_send_function(
  p_function_history_id bigint
)
returns void
language plpgsql
as $function$
declare
  v_publish_token uuid;
  v_edge_base_url text;
  v_response extensions.http_response;
  v_body jsonb;
begin
  select q.publish_token
  into v_publish_token
  from archive.github_push_queue q
  where q.function_history_id = p_function_history_id
    and q.status = 'pending';

  if v_publish_token is null then
    raise exception 'pending queue item not found';
  end if;

  select edge_base_url
  into v_edge_base_url
  from archive.function_versioning_settings
  where singleton = true;

  if v_edge_base_url is null then
    raise exception 'function versioning edge_base_url is not configured';
  end if;

  v_response := extensions.http((
    'POST',
    rtrim(v_edge_base_url, '/') || '/github-send',
    array[
      extensions.http_header('Content-Type', 'application/json')
    ],
    'application/json',
    jsonb_build_object(
      'function_history_id', p_function_history_id,
      'publish_token', v_publish_token
    )::text
  )::extensions.http_request);

  if v_response.status < 200 or v_response.status >= 300 then
    raise exception
      'github-send HTTP %: %',
      v_response.status,
      left(coalesce(v_response.content, ''), 1000);
  end if;

  v_body := v_response.content::jsonb;

  if coalesce((v_body->>'ok')::boolean, false) is not true then
    raise exception
      'github-send failed: %',
      coalesce(v_body->>'error', v_response.content);
  end if;
end;
$function$;

create or replace function archive.process_github_push_queue(
  p_limit integer default 5
)
returns integer
language plpgsql
as $function$
declare
  r record;
  v_count integer := 0;
begin
  for r in
    select id, function_history_id, try_count
    from archive.github_push_queue
    where status = 'pending'
      and try_count < 10
    order by id
    limit greatest(p_limit, 0)
    for update skip locked
  loop
    begin
      perform archive.github_send_function(r.function_history_id);

      update archive.github_push_queue
      set status = 'done',
          pushed_at = now(),
          last_error = null
      where id = r.id;

      v_count := v_count + 1;
    exception when others then
      update archive.github_push_queue
      set try_count = try_count + 1,
          last_error = SQLERRM,
          status = case
            when try_count + 1 >= 10 then 'dead'
            else 'pending'
          end
      where id = r.id;
    end;
  end loop;

  return v_count;
end;
$function$;

create or replace function archive.github_push_queue_summary()
returns table(
  status text,
  item_count bigint,
  min_created_at timestamptz,
  max_created_at timestamptz,
  max_try_count integer
)
language sql
stable
as $function$
  select
    q.status,
    count(*),
    min(q.created_at),
    max(q.created_at),
    max(q.try_count)
  from archive.github_push_queue q
  group by q.status
  order by q.status;
$function$;

create or replace function archive.requeue_dead_github_push_queue(
  p_limit integer default 100
)
returns integer
language plpgsql
as $function$
declare
  v_count integer;
begin
  with target_rows as (
    select q.id
    from archive.github_push_queue q
    where q.status = 'dead'
    order by q.id
    limit p_limit
    for update skip locked
  )
  update archive.github_push_queue q
  set status = 'pending',
      try_count = 0,
      last_error = null,
      publish_token = extensions.gen_random_uuid()
  from target_rows t
  where q.id = t.id;

  get diagnostics v_count = row_count;
  return v_count;
end;
$function$;

create or replace function archive.retry_dead_github_push_queue(
  p_requeue_limit integer default 100,
  p_process_limit integer default 20
)
returns integer
language plpgsql
as $function$
declare
  v_requeued integer;
begin
  v_requeued := archive.requeue_dead_github_push_queue(p_requeue_limit);

  if v_requeued > 0 then
    perform archive.process_github_push_queue(p_process_limit);
  end if;

  return v_requeued;
end;
$function$;

create or replace function archive.get_github_push_queue_dead_items(
  p_limit integer default 50
)
returns table(
  queue_id bigint,
  function_history_id bigint,
  schema_name text,
  function_name text,
  args text,
  return_type text,
  try_count integer,
  last_error text,
  created_at timestamptz
)
language sql
stable
as $function$
  select
    q.id,
    q.function_history_id,
    fh.schema_name,
    fh.function_name,
    fh.args,
    fh.return_type,
    q.try_count,
    q.last_error,
    q.created_at
  from archive.github_push_queue q
  join archive.function_history fh
    on fh.id = q.function_history_id
  where q.status = 'dead'
  order by q.id desc
  limit p_limit;
$function$;

create or replace function archive.push_updated_functions_to_github(
  p_schema text default 'public',
  p_immediate_limit integer default 40
)
returns integer
language plpgsql
as $function$
declare
  v_count integer;
begin
  insert into archive.github_push_queue(function_history_id)
  select function_history_id
  from archive.update_functions(p_schema)
  on conflict (function_history_id) do nothing;

  get diagnostics v_count = row_count;

  if p_immediate_limit > 0 then
    perform archive.process_github_push_queue(p_immediate_limit);
  end if;

  return v_count;
end;
$function$;

create or replace function archive.bootstrap_functions_to_github(
  p_schema text default 'public',
  p_immediate_limit integer default 50
)
returns integer
language plpgsql
as $function$
declare
  v_count integer;
begin
  insert into archive.github_push_queue(function_history_id)
  select id
  from archive.function_history
  where schema_name = p_schema
    and active = true
  on conflict (function_history_id) do nothing;

  get diagnostics v_count = row_count;

  if p_immediate_limit > 0 then
    perform archive.process_github_push_queue(p_immediate_limit);
  end if;

  return v_count;
end;
$function$;

create or replace function archive.push()
returns void
language plpgsql
as $function$
begin
  perform archive.push_updated_functions_to_github('archive');
  perform archive.push_updated_functions_to_github('private');
  perform archive.push_updated_functions_to_github('public');
end;
$function$;

create or replace function archive.push_cron()
returns void
language plpgsql
as $function$
begin
  perform archive.push();
end;
$function$;

revoke all on schema archive from public;
revoke all on all tables in schema archive from public, anon, authenticated;
revoke all on all functions in schema archive from public, anon, authenticated;
