
-- starter source: docs/templates/db-function-versioning/10_history/060_table_history.sql
create table if not exists archive.table_history (
    id bigserial primary key,
    schema_name text not null,
    table_name text not null,
    ddl text not null,
    updated_at timestamptz not null default now(),
    version integer not null default 1,
    active boolean not null default false,
    dropped boolean not null default false
);

alter table archive.table_history
    add column if not exists dropped boolean not null default false;

create index if not exists table_history_lookup_idx
    on archive.table_history (schema_name, table_name, id desc);

create index if not exists table_history_active_idx
    on archive.table_history (schema_name, table_name)
    where active = true;


-- starter source: docs/templates/db-function-versioning/10_history/070_build_table_ddl.sql
CREATE OR REPLACE FUNCTION archive.build_table_ddl(table_name text, schema_name text DEFAULT 'public'::text)
 RETURNS text
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_table_oid oid;
  v_cols text;
  v_constraints text;
  v_body text;
  v_indexes text;
  v_triggers text;
  v_policies text;
  v_rls_enabled boolean;
  v_rls_forced boolean;
  v_ddl text;
BEGIN
  SELECT c.oid, c.relrowsecurity, c.relforcerowsecurity
  INTO v_table_oid, v_rls_enabled, v_rls_forced
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = build_table_ddl.schema_name
    AND c.relname = build_table_ddl.table_name
    AND c.relkind IN ('r', 'p');

  IF v_table_oid IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT string_agg(col_def, E',\n  ' ORDER BY attnum)
  INTO v_cols
  FROM (
    SELECT
      a.attnum,
      format(
        '%I %s%s%s%s',
        a.attname,
        format_type(a.atttypid, a.atttypmod),
        CASE
          WHEN a.attidentity = 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
          WHEN a.attidentity = 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
          ELSE ''
        END,
        CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END,
        CASE
          WHEN d.adbin IS NOT NULL THEN ' DEFAULT ' || pg_get_expr(d.adbin, d.adrelid)
          ELSE ''
        END
      ) AS col_def
    FROM pg_attribute a
    LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
    WHERE a.attrelid = v_table_oid
      AND a.attnum > 0
      AND NOT a.attisdropped
  ) cols;

  SELECT string_agg(
    format('CONSTRAINT %I %s', conname, pg_get_constraintdef(oid, true)),
    E',\n  '
    ORDER BY conname
  )
  INTO v_constraints
  FROM pg_constraint
  WHERE conrelid = v_table_oid
    AND contype IN ('p', 'u', 'c', 'f', 'x');

  v_body := v_cols;
  IF v_constraints IS NOT NULL AND v_constraints <> '' THEN
    v_body := v_body || E',\n  ' || v_constraints;
  END IF;

  v_ddl := format(E'CREATE TABLE %I.%I (\n  %s\n);\n', build_table_ddl.schema_name, build_table_ddl.table_name, v_body);

  SELECT string_agg(pg_get_indexdef(i.indexrelid), E';\n')
  INTO v_indexes
  FROM pg_index i
  WHERE i.indrelid = v_table_oid
    AND NOT i.indisprimary
    AND NOT EXISTS (
      SELECT 1 FROM pg_constraint c WHERE c.conindid = i.indexrelid
    );

  IF v_indexes IS NOT NULL AND v_indexes <> '' THEN
    v_ddl := v_ddl || v_indexes || E';\n';
  END IF;

  SELECT string_agg(pg_get_triggerdef(t.oid), E';\n')
  INTO v_triggers
  FROM pg_trigger t
  WHERE t.tgrelid = v_table_oid
    AND NOT t.tgisinternal;

  IF v_triggers IS NOT NULL AND v_triggers <> '' THEN
    v_ddl := v_ddl || v_triggers || E';\n';
  END IF;

  IF v_rls_enabled THEN
    v_ddl := v_ddl || format(E'ALTER TABLE %I.%I ENABLE ROW LEVEL SECURITY;\n', build_table_ddl.schema_name, build_table_ddl.table_name);
  END IF;

  IF v_rls_forced THEN
    v_ddl := v_ddl || format(E'ALTER TABLE %I.%I FORCE ROW LEVEL SECURITY;\n', build_table_ddl.schema_name, build_table_ddl.table_name);
  END IF;

  SELECT string_agg(policy_def, E';\n')
  INTO v_policies
  FROM (
    SELECT
      format(
        'CREATE POLICY %I ON %I.%I%s TO %s%s%s',
        pol.polname,
        build_table_ddl.schema_name,
        build_table_ddl.table_name,
        CASE pol.polcmd
          WHEN 'r' THEN ' FOR SELECT'
          WHEN 'a' THEN ' FOR INSERT'
          WHEN 'w' THEN ' FOR UPDATE'
          WHEN 'd' THEN ' FOR DELETE'
          WHEN '*' THEN ''
          ELSE ''
        END,
        CASE
          WHEN array_length(pol.polroles, 1) IS NULL OR 0 = ANY(pol.polroles) THEN 'PUBLIC'
          ELSE (
            SELECT string_agg(quote_ident(r.rolname), ', ')
            FROM pg_roles r
            WHERE r.oid = ANY(pol.polroles)
          )
        END,
        CASE WHEN pol.polqual IS NOT NULL THEN ' USING (' || pg_get_expr(pol.polqual, pol.polrelid) || ')' ELSE '' END,
        CASE WHEN pol.polwithcheck IS NOT NULL THEN ' WITH CHECK (' || pg_get_expr(pol.polwithcheck, pol.polrelid) || ')' ELSE '' END
      ) AS policy_def
    FROM pg_policy pol
    WHERE pol.polrelid = v_table_oid
  ) policies;

  IF v_policies IS NOT NULL AND v_policies <> '' THEN
    v_ddl := v_ddl || v_policies || E';\n';
  END IF;

  RETURN v_ddl;
END;
$function$;


-- starter source: docs/templates/db-function-versioning/10_history/080_save_table_history.sql
create or replace function archive.save_table_history(
    p_table_name text,
    p_ddl text,
    p_schema_name text default 'public'
)
returns void
language plpgsql
security definer
set search_path to 'public', 'archive'
as $function$
declare
    v_prev_id bigint;
    v_prev_ddl text;
    v_prev_dropped boolean;
    v_next_version integer;
begin
    select th.id, th.ddl, th.dropped
    into v_prev_id, v_prev_ddl, v_prev_dropped
    from archive.table_history th
    where th.schema_name = p_schema_name
      and th.table_name = p_table_name
    order by th.id desc
    limit 1;

    if v_prev_ddl is not null
       and not coalesce(v_prev_dropped, false)
       and not exists (select 1 from archive.diff_text(v_prev_ddl, p_ddl))
    then
        update archive.table_history th
        set active = false
        where th.schema_name = p_schema_name
          and th.table_name = p_table_name;

        update archive.table_history
        set active = true
        where id = v_prev_id;

        return;
    end if;

    select coalesce(max(th.version), 0) + 1
    into v_next_version
    from archive.table_history th
    where th.schema_name = p_schema_name
      and th.table_name = p_table_name;

    update archive.table_history th
    set active = false
    where th.schema_name = p_schema_name
      and th.table_name = p_table_name;

    insert into archive.table_history (
        schema_name, table_name, ddl, version, active, dropped
    )
    values (
        p_schema_name, p_table_name, p_ddl, v_next_version, true, false
    );
end;
$function$;


-- starter source: docs/templates/db-function-versioning/10_history/090_setup_table_history.sql
CREATE OR REPLACE FUNCTION archive.setup_table_history(schema_name text DEFAULT 'public'::text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
  table_record record;
  v_ddl text;
BEGIN
  UPDATE archive.table_history th
  SET active = false
  WHERE th.schema_name = setup_table_history.schema_name;

  FOR table_record IN (
    SELECT
      n.nspname AS schema_name,
      c.relname AS table_name
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = setup_table_history.schema_name
      AND c.relkind IN ('r', 'p')
  )
  LOOP
    v_ddl := archive.build_table_ddl(table_record.table_name, table_record.schema_name);

    PERFORM archive.save_table_history(
      table_record.table_name,
      v_ddl,
      table_record.schema_name
    );
  END LOOP;
END;
$function$;


-- starter source: docs/templates/db-function-versioning/10_history/100_update_table_history.sql
create or replace function archive.update_table_history(
    p_table_name text,
    p_ddl text,
    p_schema_name text default 'public'
)
returns boolean
language plpgsql
security definer
set search_path to 'public', 'archive'
as $function$
declare
    v_prev_id bigint;
    v_prev_ddl text;
    v_prev_active boolean;
    v_prev_dropped boolean;
    v_next_version integer;
begin
    select th.id, th.ddl, th.active, th.dropped
    into v_prev_id, v_prev_ddl, v_prev_active, v_prev_dropped
    from archive.table_history th
    where th.schema_name = p_schema_name
      and th.table_name = p_table_name
    order by th.id desc
    limit 1;

    if v_prev_ddl is not null
       and not coalesce(v_prev_dropped, false)
       and not exists (select 1 from archive.diff_text(v_prev_ddl, p_ddl))
    then
        if not coalesce(v_prev_active, false) then
            update archive.table_history th
            set active = false
            where th.schema_name = p_schema_name
              and th.table_name = p_table_name;

            update archive.table_history
            set active = true
            where id = v_prev_id;
        end if;

        return false;
    end if;

    select coalesce(max(th.version), 0) + 1
    into v_next_version
    from archive.table_history th
    where th.schema_name = p_schema_name
      and th.table_name = p_table_name;

    update archive.table_history th
    set active = false
    where th.schema_name = p_schema_name
      and th.table_name = p_table_name;

    insert into archive.table_history (
        schema_name, table_name, ddl, version, active, dropped
    )
    values (
        p_schema_name, p_table_name, p_ddl, v_next_version, true, false
    );

    return true;
end;
$function$;


-- starter source: docs/templates/db-function-versioning/10_history/110_update_tables.sql
create or replace function archive.update_tables(
    p_schema_name text default 'public'
)
returns table (
    table_history_id bigint,
    schema_name text,
    table_name text
)
language plpgsql
as $function$
declare
    v_table record;
    v_changed boolean;
    v_last_id bigint;
    v_ddl text;
    v_previous_tables text[];
    v_dropped_table text;
    v_next_version integer;
begin
    select coalesce(array_agg(th.table_name order by th.table_name), array[]::text[])
    into v_previous_tables
    from archive.table_history th
    where th.schema_name = p_schema_name
      and th.active = true
      and not th.dropped;

    update archive.table_history th
    set active = false
    where th.schema_name = p_schema_name;

    for v_table in
        select
            n.nspname as schema_name,
            c.relname as table_name
        from pg_catalog.pg_class c
        join pg_catalog.pg_namespace n on n.oid = c.relnamespace
        where n.nspname = p_schema_name
          and c.relkind in ('r', 'p')
        order by c.relname
    loop
        v_ddl := archive.build_table_ddl(v_table.table_name, v_table.schema_name);

        v_changed := archive.update_table_history(
            v_table.table_name,
            v_ddl,
            v_table.schema_name
        );

        if v_changed then
            select th.id
            into v_last_id
            from archive.table_history th
            where th.schema_name = v_table.schema_name
              and th.table_name = v_table.table_name
            order by th.id desc
            limit 1;

            table_history_id := v_last_id;
            schema_name := v_table.schema_name;
            table_name := v_table.table_name;
            return next;
        end if;
    end loop;

    foreach v_dropped_table in array v_previous_tables
    loop
        if not exists (
            select 1
            from pg_catalog.pg_class c
            join pg_catalog.pg_namespace n on n.oid = c.relnamespace
            where n.nspname = p_schema_name
              and c.relname = v_dropped_table
              and c.relkind in ('r', 'p')
        ) then
            select coalesce(max(th.version), 0) + 1
            into v_next_version
            from archive.table_history th
            where th.schema_name = p_schema_name
              and th.table_name = v_dropped_table;

            insert into archive.table_history (
                schema_name,
                table_name,
                ddl,
                version,
                active,
                dropped
            )
            values (
                p_schema_name,
                v_dropped_table,
                format('DROP TABLE %I.%I;', p_schema_name, v_dropped_table),
                v_next_version,
                false,
                true
            )
            returning id into v_last_id;

            table_history_id := v_last_id;
            schema_name := p_schema_name;
            table_name := v_dropped_table;
            return next;
        end if;
    end loop;
end;
$function$;


alter table archive.github_push_queue
  add column if not exists item_type text not null default 'function',
  add column if not exists table_history_id bigint null,
  add column if not exists schema_name text null;

alter table archive.github_push_queue
  alter column function_history_id drop not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid='archive.github_push_queue'::regclass
      and conname='github_push_queue_item_type_check'
  ) then
    alter table archive.github_push_queue
      add constraint github_push_queue_item_type_check
      check (item_type in ('function','table_bundle'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid='archive.github_push_queue'::regclass
      and conname='github_push_queue_item_ref_check'
  ) then
    alter table archive.github_push_queue
      add constraint github_push_queue_item_ref_check
      check (
        (item_type='function'
          and function_history_id is not null
          and table_history_id is null
          and schema_name is null)
        or
        (item_type='table_bundle'
          and function_history_id is null
          and table_history_id is not null
          and schema_name is not null)
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid='archive.github_push_queue'::regclass
      and conname='github_push_queue_table_history_id_fkey'
  ) then
    alter table archive.github_push_queue
      add constraint github_push_queue_table_history_id_fkey
      foreign key (table_history_id)
      references archive.table_history(id)
      on delete cascade;
  end if;
end
$$;

create unique index if not exists github_push_queue_table_history_id_uidx
  on archive.github_push_queue(table_history_id)
  where item_type='table_bundle';

create or replace function public.get_table_publish_payload(
  p_table_history_id bigint,
  p_publish_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_schema_name text;
  v_payload jsonb;
begin
  if not exists (
    select 1
    from archive.github_push_queue q
    where q.item_type='table_bundle'
      and q.table_history_id=p_table_history_id
      and q.publish_token=p_publish_token
      and q.status='pending'
      and q.try_count < 10
  ) then
    raise exception 'invalid or inactive table publish token'
      using errcode='42501';
  end if;

  select q.schema_name
  into v_schema_name
  from archive.github_push_queue q
  where q.item_type='table_bundle'
    and q.table_history_id=p_table_history_id;

  if v_schema_name is null then
    raise exception 'table bundle queue row not found'
      using errcode='P0002';
  end if;

  select jsonb_build_object(
    'schema', v_schema_name,
    'tables', coalesce(
      jsonb_agg(
        jsonb_build_object(
          'table_name', th.table_name,
          'ddl', archive.redact_function_source(th.ddl)
        )
        order by th.table_name
      ),
      '[]'::jsonb
    )
  )
  into v_payload
  from archive.table_history th
  where th.schema_name=v_schema_name
    and th.active=true
    and th.dropped=false;

  return v_payload;
end;
$function$;

revoke all on function public.get_table_publish_payload(bigint, uuid)
from public, anon, authenticated;
grant execute on function public.get_table_publish_payload(bigint, uuid)
to service_role;

create or replace function archive.github_send_tables(
  p_table_history_id bigint
)
returns void
language plpgsql
as $function$
declare
  v_publish_token uuid;
  v_edge_base_url text;
  v_response extensions.http_response;
  v_body jsonb;
begin
  select q.publish_token
  into v_publish_token
  from archive.github_push_queue q
  where q.item_type='table_bundle'
    and q.table_history_id=p_table_history_id
    and q.status='pending';

  if v_publish_token is null then
    raise exception 'pending table bundle queue item not found';
  end if;

  select edge_base_url
  into v_edge_base_url
  from archive.function_versioning_settings
  where singleton=true;

  if v_edge_base_url is null then
    raise exception 'function versioning edge_base_url is not configured';
  end if;

  v_response := extensions.http((
    'POST',
    rtrim(v_edge_base_url, '/') || '/github-send',
    array[extensions.http_header('Content-Type','application/json')],
    'application/json',
    jsonb_build_object(
      'table_history_id', p_table_history_id,
      'publish_token', v_publish_token
    )::text
  )::extensions.http_request);

  if v_response.status < 200 or v_response.status >= 300 then
    raise exception 'github-send HTTP %: %',
      v_response.status,
      left(coalesce(v_response.content,''),1000);
  end if;

  v_body := v_response.content::jsonb;

  if coalesce((v_body->>'ok')::boolean,false) is not true then
    raise exception 'github-send table bundle failed: %',
      coalesce(v_body->>'error',v_response.content);
  end if;
end;
$function$;

create or replace function archive.process_github_push_queue(
  p_limit integer default 5
)
returns integer
language plpgsql
as $function$
declare
  r record;
  v_count integer := 0;
begin
  for r in
    select id,item_type,function_history_id,table_history_id,try_count
    from archive.github_push_queue
    where status='pending'
      and try_count < 10
    order by id
    limit greatest(p_limit,0)
    for update skip locked
  loop
    begin
      if r.item_type='function' then
        perform archive.github_send_function(r.function_history_id);
      elsif r.item_type='table_bundle' then
        perform archive.github_send_tables(r.table_history_id);
      else
        raise exception 'unsupported queue item type: %', r.item_type;
      end if;

      update archive.github_push_queue
      set status='done',
          pushed_at=now(),
          last_error=null
      where id=r.id;

      v_count := v_count+1;
    exception when others then
      update archive.github_push_queue
      set try_count=try_count+1,
          last_error=SQLERRM,
          status=case when try_count+1 >= 10 then 'dead' else 'pending' end
      where id=r.id;
    end;
  end loop;

  return v_count;
end;
$function$;

drop function if exists archive.github_push_queue_summary();

create function archive.github_push_queue_summary()
returns table(
  item_type text,
  status text,
  item_count bigint,
  min_created_at timestamptz,
  max_created_at timestamptz,
  max_try_count integer
)
language sql
stable
as $function$
  select q.item_type,q.status,count(*),min(q.created_at),max(q.created_at),max(q.try_count)
  from archive.github_push_queue q
  group by q.item_type,q.status
  order by q.item_type,q.status;
$function$;

drop function if exists archive.get_github_push_queue_dead_items(integer);

create function archive.get_github_push_queue_dead_items(
  p_limit integer default 50
)
returns table(
  queue_id bigint,
  item_type text,
  function_history_id bigint,
  table_history_id bigint,
  schema_name text,
  object_name text,
  try_count integer,
  last_error text,
  created_at timestamptz
)
language sql
stable
as $function$
  select
    q.id,q.item_type,q.function_history_id,q.table_history_id,
    coalesce(fh.schema_name,th.schema_name),
    coalesce(fh.function_name,th.table_name),
    q.try_count,q.last_error,q.created_at
  from archive.github_push_queue q
  left join archive.function_history fh on fh.id=q.function_history_id
  left join archive.table_history th on th.id=q.table_history_id
  where q.status='dead'
  order by q.id desc
  limit p_limit;
$function$;

create or replace function archive.push_updated_functions_to_github(
  p_schema text default 'public',
  p_immediate_limit integer default 0
)
returns integer
language plpgsql
as $function$
declare
  v_count integer;
begin
  insert into archive.github_push_queue(item_type,function_history_id)
  select 'function',function_history_id
  from archive.update_functions(p_schema)
  on conflict (function_history_id) do nothing;

  get diagnostics v_count=row_count;

  if p_immediate_limit > 0 then
    perform archive.process_github_push_queue(p_immediate_limit);
  end if;

  return v_count;
end;
$function$;

create or replace function archive.push_updated_tables_to_github(
  p_schema text default 'public',
  p_immediate_limit integer default 0
)
returns integer
language plpgsql
as $function$
declare
  v_count integer;
  v_revision_id bigint;
begin
  select count(*),max(changed.table_history_id)
  into v_count,v_revision_id
  from archive.update_tables(p_schema) changed;

  if coalesce(v_count,0) > 0 then
    insert into archive.github_push_queue(item_type,table_history_id,schema_name)
    values ('table_bundle',v_revision_id,p_schema)
    on conflict (table_history_id)
      where item_type='table_bundle'
      do nothing;
  end if;

  if p_immediate_limit > 0 then
    perform archive.process_github_push_queue(p_immediate_limit);
  end if;

  return coalesce(v_count,0);
end;
$function$;

create or replace function archive.bootstrap_functions_to_github(
  p_schema text default 'public',
  p_immediate_limit integer default 0
)
returns integer
language plpgsql
as $function$
declare
  v_count integer;
begin
  insert into archive.github_push_queue(item_type,function_history_id)
  select 'function',id
  from archive.function_history
  where schema_name=p_schema
    and active=true
  on conflict (function_history_id) do nothing;

  get diagnostics v_count=row_count;

  if p_immediate_limit > 0 then
    perform archive.process_github_push_queue(p_immediate_limit);
  end if;

  return v_count;
end;
$function$;

create or replace function archive.bootstrap_tables_to_github(
  p_schema text default 'public',
  p_immediate_limit integer default 0
)
returns integer
language plpgsql
as $function$
declare
  v_revision_id bigint;
  v_count integer;
begin
  perform archive.setup_table_history(p_schema);

  select max(th.id),count(*)
  into v_revision_id,v_count
  from archive.table_history th
  where th.schema_name=p_schema
    and th.active=true
    and th.dropped=false;

  if v_revision_id is not null then
    insert into archive.github_push_queue(item_type,table_history_id,schema_name)
    values ('table_bundle',v_revision_id,p_schema)
    on conflict (table_history_id)
      where item_type='table_bundle'
      do nothing;
  end if;

  if p_immediate_limit > 0 then
    perform archive.process_github_push_queue(p_immediate_limit);
  end if;

  return coalesce(v_count,0);
end;
$function$;

create or replace function archive.push()
returns void
language plpgsql
as $function$
begin
  perform archive.push_updated_functions_to_github('archive',0);
  perform archive.push_updated_functions_to_github('private',0);
  perform archive.push_updated_functions_to_github('public',0);

  perform archive.push_updated_tables_to_github('archive',0);
  perform archive.push_updated_tables_to_github('private',0);
  perform archive.push_updated_tables_to_github('public',0);
end;
$function$;

create or replace function archive.push_cron()
returns void
language plpgsql
as $function$
begin
  perform archive.push();
end;
$function$;

create or replace function archive.process_github_push_queue_cron(
  p_limit integer default 5
)
returns integer
language plpgsql
as $function$
begin
  return archive.process_github_push_queue(p_limit);
end;
$function$;

do $$
declare v_job_id bigint;
begin
  for v_job_id in
    select jobid from cron.job
    where jobname in (
      'archive-function-push',
      'archive-versioning-scan',
      'archive-github-push-queue'
    )
  loop
    perform cron.unschedule(v_job_id);
  end loop;
end
$$;

select cron.schedule(
  'archive-versioning-scan',
  '*/10 * * * *',
  $$select archive.push_cron();$$
);

select cron.schedule(
  'archive-github-push-queue',
  '* * * * *',
  $$select archive.process_github_push_queue_cron(5);$$
);

select archive.bootstrap_tables_to_github('archive',0);
select archive.bootstrap_tables_to_github('private',0);
select archive.bootstrap_tables_to_github('public',0);

revoke all on archive.table_history from public,anon,authenticated;
revoke all on all functions in schema archive from public,anon,authenticated;
