-- Historical migration marker.
-- This version already exists in the linked DanceApp remote migration history.
-- Original legacy DDL is intentionally not replayed in dance-crm.
-- Clean schema work starts after this reconciled history.
-- Original migration: 20260926191106_fix_style_self_rls_current_dancer
