
create table public.styles_levels (
  id bigint generated by default as identity primary key,
  style_id smallint not null references public.l_dance_style(id) on delete cascade,
  code text not null,
  title_en text not null,
  title_ru text,
  title_sr text,
  rank_order smallint not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (style_id, code),
  unique (id, style_id)
);

alter table public.styles_levels enable row level security;

grant select on public.styles_levels to anon, authenticated;

create policy styles_levels_read_active
on public.styles_levels
for select
to anon, authenticated
using (active);

create table public.dancer_style_profile (
  id uuid primary key default extensions.gen_random_uuid(),
  dancer_id uuid not null references public.dancer(id) on delete cascade,
  style_id smallint not null references public.l_dance_style(id) on delete cascade,
  is_leader boolean not null,
  is_trainer boolean not null default false,
  is_default boolean not null default false,
  level_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (dancer_id, style_id, is_leader),
  foreign key (level_id, style_id)
    references public.styles_levels(id, style_id)
    on delete set null
);

create unique index dancer_style_profile_one_default
on public.dancer_style_profile (dancer_id, style_id)
where is_default;

create index dancer_style_profile_dancer_style_idx
on public.dancer_style_profile (dancer_id, style_id);

create trigger dancer_style_profile_touch_updated_at
before update on public.dancer_style_profile
for each row execute function private.touch_updated_at();

alter table public.dancer_style_profile enable row level security;

grant select, delete on public.dancer_style_profile to authenticated;
grant insert (dancer_id, style_id, is_leader, is_default, level_id)
on public.dancer_style_profile to authenticated;
grant update (is_leader, is_default, level_id)
on public.dancer_style_profile to authenticated;

create policy dancer_style_profile_select_own
on public.dancer_style_profile
for select
to authenticated
using (dancer_id = private.current_dancer_id());

create policy dancer_style_profile_insert_own
on public.dancer_style_profile
for insert
to authenticated
with check (dancer_id = private.current_dancer_id());

create policy dancer_style_profile_update_own
on public.dancer_style_profile
for update
to authenticated
using (dancer_id = private.current_dancer_id())
with check (dancer_id = private.current_dancer_id());

create policy dancer_style_profile_delete_own
on public.dancer_style_profile
for delete
to authenticated
using (dancer_id = private.current_dancer_id());

insert into public.styles_levels (
  style_id,
  code,
  title_en,
  title_ru,
  rank_order
)
select id, 'novice', 'Novice', 'Новичок', 10
from public.l_dance_style
where title_en = 'West-Coast Swing'
on conflict (style_id, code) do update
set title_en = excluded.title_en,
    title_ru = excluded.title_ru,
    rank_order = excluded.rank_order,
    active = true;

do $$
declare
  v_style record;
  v_has_trainer boolean;
begin
  for v_style in
    select id, table_name
    from public.l_dance_style
    where table_name is not null
      and table_name ~ '^dancer_[a-z0-9_]+$'
    order by id
  loop
    select exists (
      select 1
      from information_schema.columns c
      where c.table_schema = 'public'
        and c.table_name = v_style.table_name
        and c.column_name = 'is_trainer'
    )
    into v_has_trainer;

    if v_has_trainer then
      execute format(
        'insert into public.dancer_style_profile (
           dancer_id,
           style_id,
           is_leader,
           is_trainer,
           is_default,
           created_at,
           updated_at
         )
         select
           t.id,
           %s::smallint,
           coalesce(t.main_role, d.primary_role) = 1,
           coalesce(t.is_trainer, false),
           true,
           t.created_at,
           t.created_at
         from public.%I t
         join public.dancer d on d.id = t.id
         where coalesce(t.main_role, d.primary_role) in (1, 2)
         on conflict (dancer_id, style_id, is_leader) do update
         set is_trainer = public.dancer_style_profile.is_trainer or excluded.is_trainer,
             is_default = true',
        v_style.id,
        v_style.table_name
      );
    else
      execute format(
        'insert into public.dancer_style_profile (
           dancer_id,
           style_id,
           is_leader,
           is_trainer,
           is_default,
           created_at,
           updated_at
         )
         select
           t.id,
           %s::smallint,
           coalesce(t.main_role, d.primary_role) = 1,
           false,
           true,
           t.created_at,
           t.created_at
         from public.%I t
         join public.dancer d on d.id = t.id
         where coalesce(t.main_role, d.primary_role) in (1, 2)
         on conflict (dancer_id, style_id, is_leader) do update
         set is_default = true',
        v_style.id,
        v_style.table_name
      );
    end if;
  end loop;
end
$$;

insert into public.dancer_style_profile (
  dancer_id,
  style_id,
  is_leader,
  is_trainer,
  is_default
)
select
  dsr.dancer_id,
  dsr.style_id,
  dsr.role_id = 1,
  false,
  false
from public.dancer_style_roles dsr
where dsr.role_id in (1, 2)
on conflict (dancer_id, style_id, is_leader) do nothing;

update public.dancer_style_profile p
set is_trainer = true
from public.dancer d, public.l_dance_style s
where p.dancer_id = d.id
  and p.style_id = s.id
  and d.telegram_username = 'InessaKizomba'
  and s.title_en in ('Bachata', 'Kizomba', 'Salsa');

insert into public.dancer_style_profile (
  dancer_id,
  style_id,
  is_leader,
  is_trainer,
  is_default,
  level_id
)
select
  d.id,
  s.id,
  roles.is_leader,
  false,
  roles.is_default,
  l.id
from public.dancer d
join public.l_dance_style s
  on s.title_en = 'West-Coast Swing'
join public.styles_levels l
  on l.style_id = s.id
 and l.code = 'novice'
cross join (
  values
    (false, true),
    (true, false)
) as roles(is_leader, is_default)
where d.telegram_username = 'Jellu_jane'
on conflict (dancer_id, style_id, is_leader) do update
set level_id = excluded.level_id,
    is_default = excluded.is_default;

update public.dancer_style_profile p
set is_default = false
from public.dancer d, public.l_dance_style s
where p.dancer_id = d.id
  and p.style_id = s.id
  and d.telegram_username = 'Jellu_jane'
  and s.title_en = 'West-Coast Swing'
  and p.is_leader = true;

update public.dancer_style_profile p
set is_default = true
from public.dancer d, public.l_dance_style s
where p.dancer_id = d.id
  and p.style_id = s.id
  and d.telegram_username = 'Jellu_jane'
  and s.title_en = 'West-Coast Swing'
  and p.is_leader = false;

create or replace function private.default_dance_role_for_style(
  p_dancer_id uuid,
  p_style_id smallint
)
returns smallint
language sql
stable
security invoker
set search_path = ''
as $function$
  select coalesce(
    (
      select case when p.is_leader then 1::smallint else 2::smallint end
      from public.dancer_style_profile p
      where p.dancer_id = p_dancer_id
        and p.style_id = p_style_id
      order by p.is_default desc, p.created_at, p.id
      limit 1
    ),
    (
      select d.primary_role
      from public.dancer d
      where d.id = p_dancer_id
    )
  )
$function$;

revoke all on function private.default_dance_role_for_style(uuid, smallint)
from public, anon, authenticated;

create or replace function private.dancer_can_use_role_for_style(
  p_dancer_id uuid,
  p_style_id smallint,
  p_role_id smallint
)
returns boolean
language sql
stable
security invoker
set search_path = ''
as $function$
  select case
    when p_role_id not in (1, 2) then false
    when exists (
      select 1
      from public.dancer_style_profile p
      where p.dancer_id = p_dancer_id
        and p.style_id = p_style_id
    )
    then exists (
      select 1
      from public.dancer_style_profile p
      where p.dancer_id = p_dancer_id
        and p.style_id = p_style_id
        and p.is_leader = (p_role_id = 1)
    )
    else p_role_id = private.default_dance_role_for_style(
      p_dancer_id,
      p_style_id
    )
  end
$function$;

revoke all on function private.dancer_can_use_role_for_style(uuid, smallint, smallint)
from public, anon, authenticated;

create or replace function private.dancer_styles_context(
  p_dancer_id uuid
)
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $function$
  with profiles as (
    select
      p.id,
      p.dancer_id,
      p.style_id,
      p.is_leader,
      p.is_trainer,
      p.is_default,
      p.level_id,
      p.created_at,
      case when p.is_leader then 1::smallint else 2::smallint end as role_id,
      l.code as level_code,
      l.title_en as level_title_en,
      l.title_ru as level_title_ru,
      l.title_sr as level_title_sr,
      l.rank_order as level_rank_order
    from public.dancer_style_profile p
    left join public.styles_levels l
      on l.id = p.level_id
     and l.style_id = p.style_id
    where p.dancer_id = p_dancer_id
  ),
  grouped as (
    select
      s.id,
      s.title_en,
      s.title_ru,
      s.title_sr,
      s.is_partner_dance,
      coalesce(
        max(p.role_id) filter (where p.is_default),
        min(p.role_id)
      ) as main_role,
      bool_or(p.is_trainer) as is_trainer,
      jsonb_agg(
        distinct p.role_id
        order by p.role_id
      ) as role_ids,
      jsonb_agg(
        jsonb_build_object(
          'id', p.id,
          'is_leader', p.is_leader,
          'is_trainer', p.is_trainer,
          'is_default', p.is_default,
          'level_id', p.level_id,
          'level',
            case
              when p.level_id is null then null
              else jsonb_build_object(
                'code', p.level_code,
                'title_en', p.level_title_en,
                'title_ru', p.level_title_ru,
                'title_sr', p.level_title_sr,
                'rank_order', p.level_rank_order
              )
            end
        )
        order by p.is_default desc, p.is_leader desc, p.created_at
      ) as profiles
    from profiles p
    join public.l_dance_style s on s.id = p.style_id
    group by
      s.id,
      s.title_en,
      s.title_ru,
      s.title_sr,
      s.is_partner_dance
  )
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', g.id,
        'title_en', g.title_en,
        'title_ru', g.title_ru,
        'title_sr', g.title_sr,
        'is_partner_dance', g.is_partner_dance,
        'main_role', g.main_role,
        'role_ids', g.role_ids,
        'is_trainer', g.is_trainer,
        'profiles', g.profiles
      )
      order by g.id
    ),
    '[]'::jsonb
  )
  from grouped g
$function$;

revoke all on function private.dancer_styles_context(uuid)
from public, anon, authenticated;
grant execute on function private.dancer_styles_context(uuid)
to authenticated;

create or replace function public.get_my_dancer_context()
returns jsonb
language plpgsql
stable
security invoker
set search_path = ''
as $function$
declare
  v_dancer_id uuid := private.current_dancer_id();
  v_dancer public.dancer%rowtype;
  v_roles jsonb;
  v_styles jsonb;
  v_style_catalog jsonb;
  v_dance_roles jsonb;
begin
  if v_dancer_id is null then
    raise exception 'dancer profile not found' using errcode = 'P0002';
  end if;

  select *
  into v_dancer
  from public.dancer d
  where d.id = v_dancer_id;

  select coalesce(jsonb_agg(r.role order by r.role), '[]'::jsonb)
  into v_roles
  from public.dancer_app_roles r
  where r.dancer_id = v_dancer_id;

  v_styles := private.dancer_styles_context(v_dancer_id);

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', s.id,
        'title_en', s.title_en,
        'title_ru', s.title_ru,
        'title_sr', s.title_sr,
        'is_partner_dance', s.is_partner_dance
      )
      order by s.id
    ),
    '[]'::jsonb
  )
  into v_style_catalog
  from public.l_dance_style s;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', r.id,
        'title_en', r.title_en,
        'title_ru', r.title_ru,
        'title_sr', r.title_sr
      )
      order by r.id
    ),
    '[]'::jsonb
  )
  into v_dance_roles
  from public.l_dance_role r;

  return jsonb_build_object(
    'dancer', jsonb_build_object(
      'id', v_dancer.id,
      'telegram_id', v_dancer.telegram_id,
      'telegram_username', v_dancer.telegram_username,
      'first_name', v_dancer.first_name,
      'last_name', v_dancer.last_name,
      'custom_name', v_dancer.custom_name,
      'lang_code', v_dancer.lang_code,
      'premium', v_dancer.premium,
      'primary_role', v_dancer.primary_role
    ),
    'roles', v_roles,
    'styles', v_styles,
    'style_catalog', v_style_catalog,
    'dance_roles', v_dance_roles
  );
end;
$function$;

create or replace function public.telegram_auth_bootstrap(
  p_telegram_id bigint,
  p_password text,
  p_user_meta_data jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_existing public.dancer%rowtype;
  v_dancer public.dancer%rowtype;
  v_user_id uuid;
  v_created boolean := false;
  v_roles jsonb;
  v_styles jsonb;
  v_style_catalog jsonb;
  v_dance_roles jsonb;
begin
  if p_telegram_id is null or p_telegram_id <= 0 then
    raise exception 'invalid telegram id' using errcode = '22023';
  end if;

  if p_password is null or length(p_password) < 24 then
    raise exception 'invalid auth password' using errcode = '22023';
  end if;

  select *
  into v_existing
  from public.dancer
  where telegram_id = p_telegram_id
  for update;

  if found and v_existing.auth_user_id is not null then
    v_user_id := v_existing.auth_user_id;
    perform public.update_user_password(v_user_id, p_password);
  else
    v_user_id := public.create_user_telegram_metadata(
      p_telegram_id,
      p_password,
      coalesce(p_user_meta_data, '{}'::jsonb)
    );
    v_created := true;

    if v_existing.id is not null then
      update public.dancer
      set auth_user_id = v_user_id
      where id = v_existing.id
        and auth_user_id is null;
    end if;
  end if;

  select *
  into v_dancer
  from public.ensure_dancer_exists(v_user_id);

  if v_dancer.id is null then
    raise exception 'failed to ensure dancer profile' using errcode = 'P0002';
  end if;

  update public.dancer
  set telegram_username = nullif(p_user_meta_data->>'username', ''),
      first_name = nullif(p_user_meta_data->>'first_name', ''),
      last_name = nullif(p_user_meta_data->>'last_name', ''),
      lang_code = coalesce(
        nullif(p_user_meta_data->>'language_code', ''),
        lang_code
      ),
      tg_user_json = coalesce(p_user_meta_data, tg_user_json)
  where id = v_dancer.id
  returning * into v_dancer;

  select coalesce(jsonb_agg(r.role order by r.role), '[]'::jsonb)
  into v_roles
  from public.dancer_app_roles r
  where r.dancer_id = v_dancer.id;

  v_styles := private.dancer_styles_context(v_dancer.id);

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', s.id,
        'title_en', s.title_en,
        'title_ru', s.title_ru,
        'title_sr', s.title_sr,
        'is_partner_dance', s.is_partner_dance
      )
      order by s.id
    ),
    '[]'::jsonb
  )
  into v_style_catalog
  from public.l_dance_style s;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', r.id,
        'title_en', r.title_en,
        'title_ru', r.title_ru,
        'title_sr', r.title_sr
      )
      order by r.id
    ),
    '[]'::jsonb
  )
  into v_dance_roles
  from public.l_dance_role r;

  return jsonb_build_object(
    'created', v_created,
    'auth_email', p_telegram_id::text || '@t.me',
    'dancer_id', v_dancer.id,
    'context', jsonb_build_object(
      'dancer', jsonb_build_object(
        'id', v_dancer.id,
        'telegram_id', v_dancer.telegram_id,
        'telegram_username', v_dancer.telegram_username,
        'first_name', v_dancer.first_name,
        'last_name', v_dancer.last_name,
        'custom_name', v_dancer.custom_name,
        'lang_code', v_dancer.lang_code,
        'premium', v_dancer.premium,
        'primary_role', v_dancer.primary_role
      ),
      'roles', v_roles,
      'styles', v_styles,
      'style_catalog', v_style_catalog,
      'dance_roles', v_dance_roles
    )
  );
end;
$function$;

create or replace function public.set_my_dance_style(
  p_style_id smallint,
  p_enabled boolean,
  p_main_role smallint default null::smallint
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $function$
declare
  v_dancer_id uuid := private.current_dancer_id();
  v_is_partner boolean;
  v_role smallint := p_main_role;
  v_is_leader boolean;
begin
  if v_dancer_id is null then
    raise exception 'dancer profile not found' using errcode = 'P0002';
  end if;

  select s.is_partner_dance
  into v_is_partner
  from public.l_dance_style s
  where s.id = p_style_id;

  if not found then
    raise exception 'dance style not found' using errcode = 'P0002';
  end if;

  if not p_enabled then
    delete from public.dancer_style_profile
    where dancer_id = v_dancer_id
      and style_id = p_style_id;

    return public.get_my_dancer_context();
  end if;

  if coalesce(v_is_partner, true) then
    if v_role is null then
      v_role := private.default_dance_role_for_style(
        v_dancer_id,
        p_style_id
      );
    end if;

    if v_role is null then
      select d.primary_role
      into v_role
      from public.dancer d
      where d.id = v_dancer_id;
    end if;

    if v_role not in (1, 2) then
      raise exception 'dance role is required for partner dance'
        using errcode = '23514';
    end if;

    v_is_leader := v_role = 1;
  else
    v_is_leader := false;
  end if;

  update public.dancer_style_profile
  set is_default = false
  where dancer_id = v_dancer_id
    and style_id = p_style_id
    and is_default;

  insert into public.dancer_style_profile (
    dancer_id,
    style_id,
    is_leader,
    is_default
  )
  values (
    v_dancer_id,
    p_style_id,
    v_is_leader,
    true
  )
  on conflict (dancer_id, style_id, is_leader)
  do update set is_default = true;

  return public.get_my_dancer_context();
end;
$function$;

drop table public.dancer_bachata;
drop table public.dancer_discofox;
drop table public.dancer_hustle;
drop table public.dancer_kizomba;
drop table public.dancer_salsa;
drop table public.dancer_wcs;
drop table public.dancer_zook;
drop table public.dancer_style_roles;

alter table public.l_dance_style
drop column table_name;
