-- Bring DanceApp infrastructure in line with the current supabase-project-starter architecture.
-- Project-specific hardening:
--   * generated DB artifacts remain live-DB -> Git outputs;
--   * schema export is a separate layer from function/table history;
--   * publication uses one-time DB tokens instead of an unauthenticated arbitrary-file endpoint;
--   * operational tables/functions are not exposed to anon/authenticated.

create extension if not exists pgcrypto with schema extensions;
create extension if not exists http with schema extensions;
create extension if not exists pg_cron;

create table if not exists public.debug_events (
  id uuid primary key default extensions.gen_random_uuid(),
  created_at timestamptz not null default now(),
  source text not null,
  message text not null,
  payload jsonb null
);

create index if not exists debug_events_created_at_idx
  on public.debug_events(created_at desc);
create index if not exists debug_events_source_idx
  on public.debug_events(source);

alter table public.debug_events enable row level security;
revoke all on public.debug_events from anon, authenticated;
grant select, insert on public.debug_events to service_role;

create table if not exists archive.schema_export_snapshots (
  id bigint generated by default as identity primary key,
  snapshot jsonb not null,
  publish_token uuid not null default extensions.gen_random_uuid(),
  created_at timestamptz not null default now(),
  published_at timestamptz null
);

create unique index if not exists schema_export_snapshots_publish_token_uidx
  on archive.schema_export_snapshots(publish_token);
create index if not exists schema_export_snapshots_created_at_idx
  on archive.schema_export_snapshots(created_at desc);

create or replace function public.get_complete_schema()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $function$
  select jsonb_build_object(
    'captured_at', now(),
    'schemas', (
      select coalesce(jsonb_agg(schema_payload order by schema_name), '[]'::jsonb)
      from (
        select
          ns.nspname as schema_name,
          jsonb_build_object(
            'name', ns.nspname,
            'enums', (
              select coalesce(jsonb_agg(
                jsonb_build_object(
                  'name', t.typname,
                  'values', (
                    select jsonb_agg(e.enumlabel order by e.enumsortorder)
                    from pg_catalog.pg_enum e
                    where e.enumtypid = t.oid
                  )
                ) order by t.typname
              ), '[]'::jsonb)
              from pg_catalog.pg_type t
              where t.typnamespace = ns.oid
                and t.typtype = 'e'
            ),
            'tables', (
              select coalesce(jsonb_agg(
                jsonb_build_object(
                  'name', c.relname,
                  'rls_enabled', c.relrowsecurity,
                  'columns', (
                    select coalesce(jsonb_agg(
                      jsonb_build_object(
                        'name', a.attname,
                        'type', pg_catalog.format_type(a.atttypid, a.atttypmod),
                        'not_null', a.attnotnull,
                        'default', pg_catalog.pg_get_expr(d.adbin, d.adrelid),
                        'identity', nullif(a.attidentity, '')
                      ) order by a.attnum
                    ), '[]'::jsonb)
                    from pg_catalog.pg_attribute a
                    left join pg_catalog.pg_attrdef d
                      on d.adrelid = a.attrelid
                     and d.adnum = a.attnum
                    where a.attrelid = c.oid
                      and a.attnum > 0
                      and not a.attisdropped
                  ),
                  'constraints', (
                    select coalesce(jsonb_agg(
                      jsonb_build_object(
                        'name', con.conname,
                        'type', con.contype,
                        'definition', pg_catalog.pg_get_constraintdef(con.oid, true)
                      ) order by con.conname
                    ), '[]'::jsonb)
                    from pg_catalog.pg_constraint con
                    where con.conrelid = c.oid
                  ),
                  'indexes', (
                    select coalesce(jsonb_agg(
                      jsonb_build_object(
                        'name', i.relname,
                        'definition', pg_catalog.pg_get_indexdef(i.oid)
                      ) order by i.relname
                    ), '[]'::jsonb)
                    from pg_catalog.pg_index ix
                    join pg_catalog.pg_class i on i.oid = ix.indexrelid
                    where ix.indrelid = c.oid
                  ),
                  'policies', (
                    select coalesce(jsonb_agg(
                      jsonb_build_object(
                        'name', pol.polname,
                        'command', pol.polcmd,
                        'roles', pol.polroles,
                        'using', pg_catalog.pg_get_expr(pol.polqual, pol.polrelid),
                        'check', pg_catalog.pg_get_expr(pol.polwithcheck, pol.polrelid)
                      ) order by pol.polname
                    ), '[]'::jsonb)
                    from pg_catalog.pg_policy pol
                    where pol.polrelid = c.oid
                  ),
                  'triggers', (
                    select coalesce(jsonb_agg(
                      jsonb_build_object(
                        'name', trg.tgname,
                        'definition', pg_catalog.pg_get_triggerdef(trg.oid, true)
                      ) order by trg.tgname
                    ), '[]'::jsonb)
                    from pg_catalog.pg_trigger trg
                    where trg.tgrelid = c.oid
                      and not trg.tgisinternal
                  )
                ) order by c.relname
              ), '[]'::jsonb)
              from pg_catalog.pg_class c
              where c.relnamespace = ns.oid
                and c.relkind in ('r', 'p')
            ),
            'views', (
              select coalesce(jsonb_agg(
                jsonb_build_object(
                  'name', c.relname,
                  'kind', case c.relkind when 'v' then 'view' else 'materialized_view' end,
                  'definition', pg_catalog.pg_get_viewdef(c.oid, true)
                ) order by c.relname
              ), '[]'::jsonb)
              from pg_catalog.pg_class c
              where c.relnamespace = ns.oid
                and c.relkind in ('v', 'm')
            ),
            'functions', (
              select coalesce(jsonb_agg(
                jsonb_build_object(
                  'name', p.proname,
                  'args', pg_catalog.pg_get_function_identity_arguments(p.oid),
                  'returns', pg_catalog.pg_get_function_result(p.oid),
                  'definition', archive.redact_function_source(pg_catalog.pg_get_functiondef(p.oid))
                ) order by p.proname, pg_catalog.pg_get_function_identity_arguments(p.oid)
              ), '[]'::jsonb)
              from pg_catalog.pg_proc p
              where p.pronamespace = ns.oid
                and p.prokind = 'f'
            )
          ) as schema_payload
        from pg_catalog.pg_namespace ns
        where ns.nspname in ('archive', 'private', 'public')
      ) s
    )
  );
$function$;

revoke all on function public.get_complete_schema()
from public, anon, authenticated;
grant execute on function public.get_complete_schema()
to service_role;

create or replace function public.refresh_schema_export()
returns bigint
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_id bigint;
begin
  insert into archive.schema_export_snapshots(snapshot)
  values (public.get_complete_schema())
  returning id into v_id;

  return v_id;
end;
$function$;

revoke all on function public.refresh_schema_export()
from public, anon, authenticated;
grant execute on function public.refresh_schema_export()
to service_role;

create or replace function public.get_schema_export_publish_payload(
  p_snapshot_id bigint,
  p_publish_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_snapshot jsonb;
begin
  select s.snapshot
  into v_snapshot
  from archive.schema_export_snapshots s
  where s.id = p_snapshot_id
    and s.publish_token = p_publish_token
    and s.published_at is null;

  if v_snapshot is null then
    raise exception 'invalid or inactive schema export publish token'
      using errcode = '42501';
  end if;

  return jsonb_build_object(
    'path', 'db/ddl.json',
    'content', jsonb_pretty(v_snapshot),
    'message', '[CF-Pages-Skip] schema export refresh: db/ddl.json'
  );
end;
$function$;

revoke all on function public.get_schema_export_publish_payload(bigint, uuid)
from public, anon, authenticated;
grant execute on function public.get_schema_export_publish_payload(bigint, uuid)
to service_role;

create or replace function public.github_send_schema_export(
  p_snapshot_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_publish_token uuid;
  v_edge_base_url text;
  v_response extensions.http_response;
  v_body jsonb;
begin
  select s.publish_token
  into v_publish_token
  from archive.schema_export_snapshots s
  where s.id = p_snapshot_id
    and s.published_at is null;

  if v_publish_token is null then
    raise exception 'pending schema export snapshot not found';
  end if;

  select s.edge_base_url
  into v_edge_base_url
  from archive.function_versioning_settings s
  where s.singleton = true;

  if v_edge_base_url is null then
    raise exception 'edge_base_url is not configured';
  end if;

  v_response := extensions.http((
    'POST',
    rtrim(v_edge_base_url, '/') || '/github-send',
    array[extensions.http_header('Content-Type', 'application/json')],
    'application/json',
    jsonb_build_object(
      'schema_export_id', p_snapshot_id,
      'publish_token', v_publish_token
    )::text
  )::extensions.http_request);

  if v_response.status < 200 or v_response.status >= 300 then
    raise exception 'github-send HTTP %: %',
      v_response.status,
      left(coalesce(v_response.content, ''), 1000);
  end if;

  v_body := v_response.content::jsonb;
  if coalesce((v_body->>'ok')::boolean, false) is not true then
    raise exception 'github-send schema export failed: %',
      coalesce(v_body->>'error', v_response.content);
  end if;

  update archive.schema_export_snapshots
  set published_at = now()
  where id = p_snapshot_id;

  return v_body;
end;
$function$;

revoke all on function public.github_send_schema_export(bigint)
from public, anon, authenticated;
grant execute on function public.github_send_schema_export(bigint)
to service_role;

create or replace function public.refresh_and_publish_schema_export()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_snapshot_id bigint;
begin
  v_snapshot_id := public.refresh_schema_export();
  return public.github_send_schema_export(v_snapshot_id);
end;
$function$;

revoke all on function public.refresh_and_publish_schema_export()
from public, anon, authenticated;
grant execute on function public.refresh_and_publish_schema_export()
to service_role;

-- The starter templates currently leave several archive helpers with a mutable
-- search_path. Pin every installed archive function after project-specific install.
do $$
declare
  r record;
begin
  for r in
    select p.oid::regprocedure::text as signature
    from pg_catalog.pg_proc p
    join pg_catalog.pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'archive'
  loop
    execute format(
      'alter function %s set search_path to pg_catalog, archive, public, extensions',
      r.signature
    );
  end loop;
end
$$;

revoke all on schema archive from public;
revoke all on all tables in schema archive from public, anon, authenticated;
revoke all on all functions in schema archive from public, anon, authenticated;
